<?php
/**
 * FileName: UnionController.class.php
 * User: Comos
 * Date: 2017/12/20 16:59
 */

namespace Admin\Controller;


use Think\Page;

class UnionController extends BaseController
{
    public function _initialize()
    {
      parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 商家加盟信息列表
     * @param $p int 当前页码
     */
    public function index($p = 1)
    {
        $pagesize = C('PAGE.PAGESIZE');
        $unionModel = M('union');
        $count = $unionModel->count();
        $list = $unionModel->order('is_ok asc,id desc')->page($p, $pagesize)->select();

        //获取分页
        $pages = new Page($count, $pagesize);
        $pages->setConfig('header', '共%TOTAL_ROW%条');
        $pages->setConfig('first', '首页');
        $pages->setConfig('last', '末页');
        $pages->setConfig('prev', '上一页');
        $pages->setConfig('next', '下一页');
        $pages->setConfig('theme', C('PAGE.THEME'));
        $pageHtml = $pages->show();

        $this->assign('list', $list);
        $this->assign('pageHtml', $pageHtml);
        $this->display();
    }

    /**
     * 删除提交记录
     * @param $id int 加盟记录ID
     */
    public function del($id)
    {
        $unionModel = M('union');
        $rs = $unionModel->delete($id);
        if ($rs === false) {
            $this->error('删除失败');
        }
        $this->success('删除成功');
    }

    /**
     * 更改记录状态
     * @param $id int 加盟记录ID
     */
    public function change($id)
    {
        $unionModel = M('union');
        $union_recorde = $unionModel->find($id);
        if (!$union_recorde) {
            $this->error('获取数据失败');
        }
        if ($union_recorde['is_ok'] == 2) {
            $is_ok = 1;
        } else {
            $is_ok = 2;
        }

        $rs = $unionModel->save(['id' => $id, 'is_ok' => $is_ok]);
        if ($rs === false) {
            $this->error('修改失败');
        }
        $this->success('修改成功');
    }
}